shopt -s direxpand

export EDITOR="vim"

export REPLYTO={{ user_info.email }}

{% if bash.use_oh_my_bash %}
# Oh My Bash Configuration
if [ -f "$HOME/.oh-my-bash/oh-my-bash.sh" ]; then
    # Set Oh My Bash variables before loading
    export OSH="$HOME/.oh-my-bash"
    export OSH_THEME="{{ bash.oh_my_bash_theme }}"
    export DISABLE_AUTO_UPDATE="true"

    # Define plugins to load
    plugins=({{ bash.oh_my_bash_plugins }})

    # Load Oh My Bash
    source "$HOME/.oh-my-bash/oh-my-bash.sh"
fi
{% else %}
# things for Bash git prompt
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    source $HOME/.bash-git-prompt/gitprompt.sh
fi
{% endif %}

# Add CWD(.) and $HOME/bin to path
export PATH=".:$HOME/bin:$PATH"

# Make LS look good
export LSCOLORS="ExGxCxDxBxegedabagaced" # Good for dark background

# Make LESS more attractive
export LESS="-BFIMRX"

#  Set the number of commands to be maintained in history within a session.
export HISTSIZE=100
#  Set the number of commands to be maintained in history across logins.
export HISTFILESIZE=100

###############################################################
# Set user-defined aliases
test -e "${HOME}/.bash_aliases" && source "${HOME}/.bash_aliases"
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

###############################################################
# Set site specific aliases and functions
test -e "${HOME}/.bash_site" && source "${HOME}/.bash_site"
